### ISSUE TITLE
TcPlayer is not a constructor

### ISSUE THREAD

**Issue by simonkes** [fralonra/vue-tcplayer#4]
已经在index.html中引入tcplayer.js，tcplayer.vue中无法获取到window.tcplayer这个构造函数。最终报TcPlayer is not a constructor错误

**Comment by simonkes** [comment]
热更新vue页面后，视频又正常了。就是第一次加载报错。

**Comment by fralonra** [comment]
有检查下网络请求吗？

**Comment by simonkes** [comment]
已经解决了。首先cnpm i TcPlayer --save; 然后将TcPlayer.vue里的const TcPlayer = window.Tcplayer替换为import {TcPlayer} from 'TcPlayer'。
